name: arthur
description: A sample command-line application.
version: 0.1.5
repository:  https://github.com/x-i-f-r-a/Arthur.git

environment:
  sdk: ^3.0.2

dependencies:
  path: ^1.8.0
  sqlite3: ^2.0.0
  postgres: ^2.6.1
  yaml: ^3.1.2 

executables:
 arthur: